/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CropId = string;
export interface CropRecord {
  'growthStage' : CropStage,
  'plantingDate' : Timestamp,
  'farmerId' : Principal,
  'expectedHarvestDate' : Timestamp,
  'name' : string,
  'variety' : [] | [string],
  'fieldId' : string,
}
export type CropStage = { 'germination' : null } |
  { 'sowing' : null } |
  { 'flowering' : null } |
  { 'completed' : null } |
  { 'harvesting' : null } |
  { 'vegetative' : null };
export interface DashboardStats {
  'totalExpensesThisMonth' : number,
  'totalFields' : bigint,
  'activeCrops' : bigint,
  'pendingTasks' : bigint,
  'lowStockItems' : bigint,
  'totalFarmers' : bigint,
}
export interface Expense {
  'title' : string,
  'date' : Timestamp,
  'notes' : [] | [string],
  'category' : ExpenseCategory,
  'amount' : number,
}
export type ExpenseCategory = { 'other' : null } |
  { 'equipment' : null } |
  { 'labour' : null } |
  { 'transport' : null } |
  { 'seeds' : null } |
  { 'irrigation' : null };
export type ExpenseId = string;
export type FarmerId = Principal;
export interface FarmerProfile {
  'contact' : [] | [string],
  'name' : string,
  'village' : [] | [string],
  'landAreaAcres' : number,
  'registrationDate' : Timestamp,
}
export interface Field {
  'status' : FieldStatus,
  'soilType' : SoilType,
  'ownerId' : Principal,
  'areaAcres' : number,
  'name' : string,
}
export type FieldId = string;
export type FieldStatus = { 'idle' : null } |
  { 'planted' : null } |
  { 'harvesting' : null };
export interface InventoryItem {
  'lowStockThreshold' : number,
  'name' : string,
  'unit' : string,
  'lastUpdated' : Timestamp,
  'quantity' : number,
  'category' : ItemCategory,
}
export type ItemCategory = { 'other' : null } |
  { 'equipment' : null } |
  { 'seeds' : null } |
  { 'fertilizer' : null } |
  { 'pesticide' : null };
export type ItemId = string;
export interface Notice {
  'title' : string,
  'postedBy' : Principal,
  'postedDate' : Timestamp,
  'message' : string,
}
export type NoticeId = string;
export type SoilType = { 'clay' : null } |
  { 'silt' : null } |
  { 'sandy' : null } |
  { 'loamy' : null };
export interface Task {
  'status' : TaskStatus,
  'title' : string,
  'assignedWorker' : WorkerId,
  'dueDate' : Timestamp,
  'description' : [] | [string],
  'priority' : TaskPriority,
  'fieldId' : FieldId,
}
export type TaskId = string;
export type TaskPriority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type TaskStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export type Timestamp = bigint;
export interface UserProfile {
  'workerId' : [] | [string],
  'name' : string,
  'role' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type WorkerId = string;
export interface WorkerProfile {
  'contact' : [] | [string],
  'dailyWage' : number,
  'name' : string,
  'joiningDate' : Timestamp,
  'skill' : WorkerSkill,
}
export type WorkerSkill = { 'harvesting' : null } |
  { 'plowing' : null } |
  { 'spraying' : null } |
  { 'irrigation' : null } |
  { 'general' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addExpense' : ActorMethod<[Expense], ExpenseId>,
  'addInventoryItem' : ActorMethod<[InventoryItem], ItemId>,
  'addWorkerProfile' : ActorMethod<[WorkerProfile], WorkerId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createFarmerProfile' : ActorMethod<[FarmerProfile], undefined>,
  'createField' : ActorMethod<[string, number, SoilType, Principal], undefined>,
  'createTask' : ActorMethod<[Task], TaskId>,
  'getAllCrops' : ActorMethod<[], Array<CropRecord>>,
  'getAllExpenses' : ActorMethod<[], Array<Expense>>,
  'getAllFarmerProfiles' : ActorMethod<[], Array<FarmerProfile>>,
  'getAllFields' : ActorMethod<[], Array<Field>>,
  'getAllInventoryItems' : ActorMethod<[], Array<InventoryItem>>,
  'getAllNotices' : ActorMethod<[], Array<Notice>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getAllWorkerProfiles' : ActorMethod<[], Array<WorkerProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCrop' : ActorMethod<[CropId], CropRecord>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getExpense' : ActorMethod<[ExpenseId], Expense>,
  'getFarmerProfile' : ActorMethod<[FarmerId], FarmerProfile>,
  'getField' : ActorMethod<[FieldId], Field>,
  'getInventoryItem' : ActorMethod<[ItemId], InventoryItem>,
  'getNotice' : ActorMethod<[NoticeId], Notice>,
  'getTask' : ActorMethod<[TaskId], Task>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkerProfile' : ActorMethod<[WorkerId], WorkerProfile>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'plantCrop' : ActorMethod<
    [string, [] | [string], string, Timestamp],
    undefined
  >,
  'postNotice' : ActorMethod<[string, string], NoticeId>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateInventoryItem' : ActorMethod<[ItemId, InventoryItem], undefined>,
  'updateTaskStatus' : ActorMethod<[TaskId, TaskStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];