/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const ExpenseCategory = IDL.Variant({
  'other' : IDL.Null,
  'equipment' : IDL.Null,
  'labour' : IDL.Null,
  'transport' : IDL.Null,
  'seeds' : IDL.Null,
  'irrigation' : IDL.Null,
});
export const Expense = IDL.Record({
  'title' : IDL.Text,
  'date' : Timestamp,
  'notes' : IDL.Opt(IDL.Text),
  'category' : ExpenseCategory,
  'amount' : IDL.Float64,
});
export const ExpenseId = IDL.Text;
export const ItemCategory = IDL.Variant({
  'other' : IDL.Null,
  'equipment' : IDL.Null,
  'seeds' : IDL.Null,
  'fertilizer' : IDL.Null,
  'pesticide' : IDL.Null,
});
export const InventoryItem = IDL.Record({
  'lowStockThreshold' : IDL.Float64,
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'lastUpdated' : Timestamp,
  'quantity' : IDL.Float64,
  'category' : ItemCategory,
});
export const ItemId = IDL.Text;
export const WorkerSkill = IDL.Variant({
  'harvesting' : IDL.Null,
  'plowing' : IDL.Null,
  'spraying' : IDL.Null,
  'irrigation' : IDL.Null,
  'general' : IDL.Null,
});
export const WorkerProfile = IDL.Record({
  'contact' : IDL.Opt(IDL.Text),
  'dailyWage' : IDL.Float64,
  'name' : IDL.Text,
  'joiningDate' : Timestamp,
  'skill' : WorkerSkill,
});
export const WorkerId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FarmerProfile = IDL.Record({
  'contact' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'village' : IDL.Opt(IDL.Text),
  'landAreaAcres' : IDL.Float64,
  'registrationDate' : Timestamp,
});
export const SoilType = IDL.Variant({
  'clay' : IDL.Null,
  'silt' : IDL.Null,
  'sandy' : IDL.Null,
  'loamy' : IDL.Null,
});
export const TaskStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const TaskPriority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const FieldId = IDL.Text;
export const Task = IDL.Record({
  'status' : TaskStatus,
  'title' : IDL.Text,
  'assignedWorker' : WorkerId,
  'dueDate' : Timestamp,
  'description' : IDL.Opt(IDL.Text),
  'priority' : TaskPriority,
  'fieldId' : FieldId,
});
export const TaskId = IDL.Text;
export const CropStage = IDL.Variant({
  'germination' : IDL.Null,
  'sowing' : IDL.Null,
  'flowering' : IDL.Null,
  'completed' : IDL.Null,
  'harvesting' : IDL.Null,
  'vegetative' : IDL.Null,
});
export const CropRecord = IDL.Record({
  'growthStage' : CropStage,
  'plantingDate' : Timestamp,
  'farmerId' : IDL.Principal,
  'expectedHarvestDate' : Timestamp,
  'name' : IDL.Text,
  'variety' : IDL.Opt(IDL.Text),
  'fieldId' : IDL.Text,
});
export const FieldStatus = IDL.Variant({
  'idle' : IDL.Null,
  'planted' : IDL.Null,
  'harvesting' : IDL.Null,
});
export const Field = IDL.Record({
  'status' : FieldStatus,
  'soilType' : SoilType,
  'ownerId' : IDL.Principal,
  'areaAcres' : IDL.Float64,
  'name' : IDL.Text,
});
export const Notice = IDL.Record({
  'title' : IDL.Text,
  'postedBy' : IDL.Principal,
  'postedDate' : Timestamp,
  'message' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'workerId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'role' : IDL.Text,
});
export const CropId = IDL.Text;
export const DashboardStats = IDL.Record({
  'totalExpensesThisMonth' : IDL.Float64,
  'totalFields' : IDL.Nat,
  'activeCrops' : IDL.Nat,
  'pendingTasks' : IDL.Nat,
  'lowStockItems' : IDL.Nat,
  'totalFarmers' : IDL.Nat,
});
export const FarmerId = IDL.Principal;
export const NoticeId = IDL.Text;

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addExpense' : IDL.Func([Expense], [ExpenseId], []),
  'addInventoryItem' : IDL.Func([InventoryItem], [ItemId], []),
  'addWorkerProfile' : IDL.Func([WorkerProfile], [WorkerId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createFarmerProfile' : IDL.Func([FarmerProfile], [], []),
  'createField' : IDL.Func(
      [IDL.Text, IDL.Float64, SoilType, IDL.Principal],
      [],
      [],
    ),
  'createTask' : IDL.Func([Task], [TaskId], []),
  'getAllCrops' : IDL.Func([], [IDL.Vec(CropRecord)], ['query']),
  'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getAllFarmerProfiles' : IDL.Func([], [IDL.Vec(FarmerProfile)], ['query']),
  'getAllFields' : IDL.Func([], [IDL.Vec(Field)], ['query']),
  'getAllInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
  'getAllNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAllWorkerProfiles' : IDL.Func([], [IDL.Vec(WorkerProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCrop' : IDL.Func([CropId], [CropRecord], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getExpense' : IDL.Func([ExpenseId], [Expense], ['query']),
  'getFarmerProfile' : IDL.Func([FarmerId], [FarmerProfile], ['query']),
  'getField' : IDL.Func([FieldId], [Field], ['query']),
  'getInventoryItem' : IDL.Func([ItemId], [InventoryItem], ['query']),
  'getNotice' : IDL.Func([NoticeId], [Notice], ['query']),
  'getTask' : IDL.Func([TaskId], [Task], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkerProfile' : IDL.Func([WorkerId], [WorkerProfile], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'plantCrop' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Text, Timestamp],
      [],
      [],
    ),
  'postNotice' : IDL.Func([IDL.Text, IDL.Text], [NoticeId], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateInventoryItem' : IDL.Func([ItemId, InventoryItem], [], []),
  'updateTaskStatus' : IDL.Func([TaskId, TaskStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const ExpenseCategory = IDL.Variant({
    'other' : IDL.Null,
    'equipment' : IDL.Null,
    'labour' : IDL.Null,
    'transport' : IDL.Null,
    'seeds' : IDL.Null,
    'irrigation' : IDL.Null,
  });
  const Expense = IDL.Record({
    'title' : IDL.Text,
    'date' : Timestamp,
    'notes' : IDL.Opt(IDL.Text),
    'category' : ExpenseCategory,
    'amount' : IDL.Float64,
  });
  const ExpenseId = IDL.Text;
  const ItemCategory = IDL.Variant({
    'other' : IDL.Null,
    'equipment' : IDL.Null,
    'seeds' : IDL.Null,
    'fertilizer' : IDL.Null,
    'pesticide' : IDL.Null,
  });
  const InventoryItem = IDL.Record({
    'lowStockThreshold' : IDL.Float64,
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'lastUpdated' : Timestamp,
    'quantity' : IDL.Float64,
    'category' : ItemCategory,
  });
  const ItemId = IDL.Text;
  const WorkerSkill = IDL.Variant({
    'harvesting' : IDL.Null,
    'plowing' : IDL.Null,
    'spraying' : IDL.Null,
    'irrigation' : IDL.Null,
    'general' : IDL.Null,
  });
  const WorkerProfile = IDL.Record({
    'contact' : IDL.Opt(IDL.Text),
    'dailyWage' : IDL.Float64,
    'name' : IDL.Text,
    'joiningDate' : Timestamp,
    'skill' : WorkerSkill,
  });
  const WorkerId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FarmerProfile = IDL.Record({
    'contact' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'village' : IDL.Opt(IDL.Text),
    'landAreaAcres' : IDL.Float64,
    'registrationDate' : Timestamp,
  });
  const SoilType = IDL.Variant({
    'clay' : IDL.Null,
    'silt' : IDL.Null,
    'sandy' : IDL.Null,
    'loamy' : IDL.Null,
  });
  const TaskStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const TaskPriority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const FieldId = IDL.Text;
  const Task = IDL.Record({
    'status' : TaskStatus,
    'title' : IDL.Text,
    'assignedWorker' : WorkerId,
    'dueDate' : Timestamp,
    'description' : IDL.Opt(IDL.Text),
    'priority' : TaskPriority,
    'fieldId' : FieldId,
  });
  const TaskId = IDL.Text;
  const CropStage = IDL.Variant({
    'germination' : IDL.Null,
    'sowing' : IDL.Null,
    'flowering' : IDL.Null,
    'completed' : IDL.Null,
    'harvesting' : IDL.Null,
    'vegetative' : IDL.Null,
  });
  const CropRecord = IDL.Record({
    'growthStage' : CropStage,
    'plantingDate' : Timestamp,
    'farmerId' : IDL.Principal,
    'expectedHarvestDate' : Timestamp,
    'name' : IDL.Text,
    'variety' : IDL.Opt(IDL.Text),
    'fieldId' : IDL.Text,
  });
  const FieldStatus = IDL.Variant({
    'idle' : IDL.Null,
    'planted' : IDL.Null,
    'harvesting' : IDL.Null,
  });
  const Field = IDL.Record({
    'status' : FieldStatus,
    'soilType' : SoilType,
    'ownerId' : IDL.Principal,
    'areaAcres' : IDL.Float64,
    'name' : IDL.Text,
  });
  const Notice = IDL.Record({
    'title' : IDL.Text,
    'postedBy' : IDL.Principal,
    'postedDate' : Timestamp,
    'message' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'workerId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  const CropId = IDL.Text;
  const DashboardStats = IDL.Record({
    'totalExpensesThisMonth' : IDL.Float64,
    'totalFields' : IDL.Nat,
    'activeCrops' : IDL.Nat,
    'pendingTasks' : IDL.Nat,
    'lowStockItems' : IDL.Nat,
    'totalFarmers' : IDL.Nat,
  });
  const FarmerId = IDL.Principal;
  const NoticeId = IDL.Text;
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addExpense' : IDL.Func([Expense], [ExpenseId], []),
    'addInventoryItem' : IDL.Func([InventoryItem], [ItemId], []),
    'addWorkerProfile' : IDL.Func([WorkerProfile], [WorkerId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createFarmerProfile' : IDL.Func([FarmerProfile], [], []),
    'createField' : IDL.Func(
        [IDL.Text, IDL.Float64, SoilType, IDL.Principal],
        [],
        [],
      ),
    'createTask' : IDL.Func([Task], [TaskId], []),
    'getAllCrops' : IDL.Func([], [IDL.Vec(CropRecord)], ['query']),
    'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getAllFarmerProfiles' : IDL.Func([], [IDL.Vec(FarmerProfile)], ['query']),
    'getAllFields' : IDL.Func([], [IDL.Vec(Field)], ['query']),
    'getAllInventoryItems' : IDL.Func([], [IDL.Vec(InventoryItem)], ['query']),
    'getAllNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAllWorkerProfiles' : IDL.Func([], [IDL.Vec(WorkerProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCrop' : IDL.Func([CropId], [CropRecord], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getExpense' : IDL.Func([ExpenseId], [Expense], ['query']),
    'getFarmerProfile' : IDL.Func([FarmerId], [FarmerProfile], ['query']),
    'getField' : IDL.Func([FieldId], [Field], ['query']),
    'getInventoryItem' : IDL.Func([ItemId], [InventoryItem], ['query']),
    'getNotice' : IDL.Func([NoticeId], [Notice], ['query']),
    'getTask' : IDL.Func([TaskId], [Task], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkerProfile' : IDL.Func([WorkerId], [WorkerProfile], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'plantCrop' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Text, Timestamp],
        [],
        [],
      ),
    'postNotice' : IDL.Func([IDL.Text, IDL.Text], [NoticeId], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateInventoryItem' : IDL.Func([ItemId, InventoryItem], [], []),
    'updateTaskStatus' : IDL.Func([TaskId, TaskStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };