/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Field {
    status: FieldStatus;
    soilType: SoilType;
    ownerId: Principal;
    areaAcres: number;
    name: string;
}
export type Timestamp = bigint;
export interface CropRecord {
    growthStage: CropStage;
    plantingDate: Timestamp;
    farmerId: Principal;
    expectedHarvestDate: Timestamp;
    name: string;
    variety?: string;
    fieldId: string;
}
export type FieldId = string;
export interface Task {
    status: TaskStatus;
    title: string;
    assignedWorker: WorkerId;
    dueDate: Timestamp;
    description?: string;
    priority: TaskPriority;
    fieldId: FieldId;
}
export type FarmerId = Principal;
export interface InventoryItem {
    lowStockThreshold: number;
    name: string;
    unit: string;
    lastUpdated: Timestamp;
    quantity: number;
    category: ItemCategory;
}
export type CropId = string;
export interface Notice {
    title: string;
    postedBy: Principal;
    postedDate: Timestamp;
    message: string;
}
export type ItemId = string;
export type NoticeId = string;
export interface Expense {
    title: string;
    date: Timestamp;
    notes?: string;
    category: ExpenseCategory;
    amount: number;
}
export interface DashboardStats {
    totalExpensesThisMonth: number;
    totalFields: bigint;
    activeCrops: bigint;
    pendingTasks: bigint;
    lowStockItems: bigint;
    totalFarmers: bigint;
}
export interface FarmerProfile {
    contact?: string;
    name: string;
    village?: string;
    landAreaAcres: number;
    registrationDate: Timestamp;
}
export interface WorkerProfile {
    contact?: string;
    dailyWage: number;
    name: string;
    joiningDate: Timestamp;
    skill: WorkerSkill;
}
export type TaskId = string;
export type ExpenseId = string;
export type WorkerId = string;
export interface UserProfile {
    workerId?: string;
    name: string;
    role: string;
}
export enum CropStage {
    germination = "germination",
    sowing = "sowing",
    flowering = "flowering",
    completed = "completed",
    harvesting = "harvesting",
    vegetative = "vegetative"
}
export enum ExpenseCategory {
    other = "other",
    equipment = "equipment",
    labour = "labour",
    transport = "transport",
    seeds = "seeds",
    irrigation = "irrigation"
}
export enum FieldStatus {
    idle = "idle",
    planted = "planted",
    harvesting = "harvesting"
}
export enum ItemCategory {
    other = "other",
    equipment = "equipment",
    seeds = "seeds",
    fertilizer = "fertilizer",
    pesticide = "pesticide"
}
export enum SoilType {
    clay = "clay",
    silt = "silt",
    sandy = "sandy",
    loamy = "loamy"
}
export enum TaskPriority {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum TaskStatus {
    pending = "pending",
    completed = "completed",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum WorkerSkill {
    harvesting = "harvesting",
    plowing = "plowing",
    spraying = "spraying",
    irrigation = "irrigation",
    general = "general"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addExpense(expense: Expense): Promise<ExpenseId>;
    addInventoryItem(item: InventoryItem): Promise<ItemId>;
    addWorkerProfile(profile: WorkerProfile): Promise<WorkerId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createFarmerProfile(profile: FarmerProfile): Promise<void>;
    createField(name: string, areaAcres: number, soilType: SoilType, ownerId: Principal): Promise<void>;
    createTask(task: Task): Promise<TaskId>;
    getAllCrops(): Promise<Array<CropRecord>>;
    getAllExpenses(): Promise<Array<Expense>>;
    getAllFarmerProfiles(): Promise<Array<FarmerProfile>>;
    getAllFields(): Promise<Array<Field>>;
    getAllInventoryItems(): Promise<Array<InventoryItem>>;
    getAllNotices(): Promise<Array<Notice>>;
    getAllTasks(): Promise<Array<Task>>;
    getAllWorkerProfiles(): Promise<Array<WorkerProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCrop(cropId: CropId): Promise<CropRecord>;
    getDashboardStats(): Promise<DashboardStats>;
    getExpense(expenseId: ExpenseId): Promise<Expense>;
    getFarmerProfile(farmerId: FarmerId): Promise<FarmerProfile>;
    getField(fieldId: FieldId): Promise<Field>;
    getInventoryItem(itemId: ItemId): Promise<InventoryItem>;
    getNotice(noticeId: NoticeId): Promise<Notice>;
    getTask(taskId: TaskId): Promise<Task>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWorkerProfile(workerId: WorkerId): Promise<WorkerProfile>;
    isCallerAdmin(): Promise<boolean>;
    plantCrop(name: string, variety: string | null, fieldId: string, expectedHarvestDate: Timestamp): Promise<void>;
    postNotice(title: string, message: string): Promise<NoticeId>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateInventoryItem(itemId: ItemId, item: InventoryItem): Promise<void>;
    updateTaskStatus(taskId: TaskId, status: TaskStatus): Promise<void>;
}
import type { CropRecord as _CropRecord, CropStage as _CropStage, Expense as _Expense, ExpenseCategory as _ExpenseCategory, FarmerProfile as _FarmerProfile, Field as _Field, FieldId as _FieldId, FieldStatus as _FieldStatus, InventoryItem as _InventoryItem, ItemCategory as _ItemCategory, SoilType as _SoilType, Task as _Task, TaskPriority as _TaskPriority, TaskStatus as _TaskStatus, Timestamp as _Timestamp, UserProfile as _UserProfile, UserRole as _UserRole, WorkerId as _WorkerId, WorkerProfile as _WorkerProfile, WorkerSkill as _WorkerSkill } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addExpense(arg0: Expense): Promise<ExpenseId> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpense(to_candid_Expense_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpense(to_candid_Expense_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addInventoryItem(arg0: InventoryItem): Promise<ItemId> {
        if (this.processError) {
            try {
                const result = await this.actor.addInventoryItem(to_candid_InventoryItem_n5(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInventoryItem(to_candid_InventoryItem_n5(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addWorkerProfile(arg0: WorkerProfile): Promise<WorkerId> {
        if (this.processError) {
            try {
                const result = await this.actor.addWorkerProfile(to_candid_WorkerProfile_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWorkerProfile(to_candid_WorkerProfile_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createFarmerProfile(arg0: FarmerProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createFarmerProfile(to_candid_FarmerProfile_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFarmerProfile(to_candid_FarmerProfile_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createField(arg0: string, arg1: number, arg2: SoilType, arg3: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createField(arg0, arg1, to_candid_SoilType_n17(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createField(arg0, arg1, to_candid_SoilType_n17(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async createTask(arg0: Task): Promise<TaskId> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(to_candid_Task_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(to_candid_Task_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllCrops(): Promise<Array<CropRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCrops();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCrops();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllExpenses(): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExpenses();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExpenses();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllFarmerProfiles(): Promise<Array<FarmerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFarmerProfiles();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFarmerProfiles();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllFields(): Promise<Array<Field>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFields();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFields();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllInventoryItems(): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInventoryItems();
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInventoryItems();
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNotices(): Promise<Array<Notice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNotices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNotices();
            return result;
        }
    }
    async getAllTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasks();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasks();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllWorkerProfiles(): Promise<Array<WorkerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWorkerProfiles();
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWorkerProfiles();
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCrop(arg0: CropId): Promise<CropRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getCrop(arg0);
                return from_candid_CropRecord_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCrop(arg0);
            return from_candid_CropRecord_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getExpense(arg0: ExpenseId): Promise<Expense> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpense(arg0);
                return from_candid_Expense_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpense(arg0);
            return from_candid_Expense_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFarmerProfile(arg0: FarmerId): Promise<FarmerProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getFarmerProfile(arg0);
                return from_candid_FarmerProfile_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFarmerProfile(arg0);
            return from_candid_FarmerProfile_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getField(arg0: FieldId): Promise<Field> {
        if (this.processError) {
            try {
                const result = await this.actor.getField(arg0);
                return from_candid_Field_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getField(arg0);
            return from_candid_Field_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInventoryItem(arg0: ItemId): Promise<InventoryItem> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryItem(arg0);
                return from_candid_InventoryItem_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryItem(arg0);
            return from_candid_InventoryItem_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotice(arg0: NoticeId): Promise<Notice> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotice(arg0);
            return result;
        }
    }
    async getTask(arg0: TaskId): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.getTask(arg0);
                return from_candid_Task_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTask(arg0);
            return from_candid_Task_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkerProfile(arg0: WorkerId): Promise<WorkerProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkerProfile(arg0);
                return from_candid_WorkerProfile_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkerProfile(arg0);
            return from_candid_WorkerProfile_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async plantCrop(arg0: string, arg1: string | null, arg2: string, arg3: Timestamp): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.plantCrop(arg0, to_candid_opt_n68(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.plantCrop(arg0, to_candid_opt_n68(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async postNotice(arg0: string, arg1: string): Promise<NoticeId> {
        if (this.processError) {
            try {
                const result = await this.actor.postNotice(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postNotice(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n69(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n69(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateInventoryItem(arg0: ItemId, arg1: InventoryItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInventoryItem(arg0, to_candid_InventoryItem_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInventoryItem(arg0, to_candid_InventoryItem_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTaskStatus(arg0: TaskId, arg1: TaskStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTaskStatus(arg0, to_candid_TaskStatus_n21(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTaskStatus(arg0, to_candid_TaskStatus_n21(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_CropRecord_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CropRecord): CropRecord {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_CropStage_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CropStage): CropStage {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_ExpenseCategory_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExpenseCategory): ExpenseCategory {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_Expense_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Expense): Expense {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_FarmerProfile_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FarmerProfile): FarmerProfile {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_FieldStatus_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FieldStatus): FieldStatus {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_Field_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Field): Field {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_InventoryItem_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InventoryItem): InventoryItem {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_ItemCategory_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ItemCategory): ItemCategory {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_SoilType_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SoilType): SoilType {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_TaskPriority_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskPriority): TaskPriority {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function from_candid_TaskStatus_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n65(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n67(_uploadFile, _downloadFile, value);
}
function from_candid_WorkerProfile_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkerProfile): WorkerProfile {
    return from_candid_record_n60(_uploadFile, _downloadFile, value);
}
function from_candid_WorkerSkill_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkerSkill): WorkerSkill {
    return from_candid_variant_n62(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n64(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    growthStage: _CropStage;
    plantingDate: _Timestamp;
    farmerId: Principal;
    expectedHarvestDate: _Timestamp;
    name: string;
    variety: [] | [string];
    fieldId: string;
}): {
    growthStage: CropStage;
    plantingDate: Timestamp;
    farmerId: Principal;
    expectedHarvestDate: Timestamp;
    name: string;
    variety?: string;
    fieldId: string;
} {
    return {
        growthStage: from_candid_CropStage_n28(_uploadFile, _downloadFile, value.growthStage),
        plantingDate: value.plantingDate,
        farmerId: value.farmerId,
        expectedHarvestDate: value.expectedHarvestDate,
        name: value.name,
        variety: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.variety)),
        fieldId: value.fieldId
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    date: _Timestamp;
    notes: [] | [string];
    category: _ExpenseCategory;
    amount: number;
}): {
    title: string;
    date: Timestamp;
    notes?: string;
    category: ExpenseCategory;
    amount: number;
} {
    return {
        title: value.title,
        date: value.date,
        notes: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.notes)),
        category: from_candid_ExpenseCategory_n34(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contact: [] | [string];
    name: string;
    village: [] | [string];
    landAreaAcres: number;
    registrationDate: _Timestamp;
}): {
    contact?: string;
    name: string;
    village?: string;
    landAreaAcres: number;
    registrationDate: Timestamp;
} {
    return {
        contact: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.contact)),
        name: value.name,
        village: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.village)),
        landAreaAcres: value.landAreaAcres,
        registrationDate: value.registrationDate
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _FieldStatus;
    soilType: _SoilType;
    ownerId: Principal;
    areaAcres: number;
    name: string;
}): {
    status: FieldStatus;
    soilType: SoilType;
    ownerId: Principal;
    areaAcres: number;
    name: string;
} {
    return {
        status: from_candid_FieldStatus_n42(_uploadFile, _downloadFile, value.status),
        soilType: from_candid_SoilType_n44(_uploadFile, _downloadFile, value.soilType),
        ownerId: value.ownerId,
        areaAcres: value.areaAcres,
        name: value.name
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lowStockThreshold: number;
    name: string;
    unit: string;
    lastUpdated: _Timestamp;
    quantity: number;
    category: _ItemCategory;
}): {
    lowStockThreshold: number;
    name: string;
    unit: string;
    lastUpdated: Timestamp;
    quantity: number;
    category: ItemCategory;
} {
    return {
        lowStockThreshold: value.lowStockThreshold,
        name: value.name,
        unit: value.unit,
        lastUpdated: value.lastUpdated,
        quantity: value.quantity,
        category: from_candid_ItemCategory_n49(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _TaskStatus;
    title: string;
    assignedWorker: _WorkerId;
    dueDate: _Timestamp;
    description: [] | [string];
    priority: _TaskPriority;
    fieldId: _FieldId;
}): {
    status: TaskStatus;
    title: string;
    assignedWorker: WorkerId;
    dueDate: Timestamp;
    description?: string;
    priority: TaskPriority;
    fieldId: FieldId;
} {
    return {
        status: from_candid_TaskStatus_n54(_uploadFile, _downloadFile, value.status),
        title: value.title,
        assignedWorker: value.assignedWorker,
        dueDate: value.dueDate,
        description: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.description)),
        priority: from_candid_TaskPriority_n56(_uploadFile, _downloadFile, value.priority),
        fieldId: value.fieldId
    };
}
function from_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contact: [] | [string];
    dailyWage: number;
    name: string;
    joiningDate: _Timestamp;
    skill: _WorkerSkill;
}): {
    contact?: string;
    dailyWage: number;
    name: string;
    joiningDate: Timestamp;
    skill: WorkerSkill;
} {
    return {
        contact: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.contact)),
        dailyWage: value.dailyWage,
        name: value.name,
        joiningDate: value.joiningDate,
        skill: from_candid_WorkerSkill_n61(_uploadFile, _downloadFile, value.skill)
    };
}
function from_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    workerId: [] | [string];
    name: string;
    role: string;
}): {
    workerId?: string;
    name: string;
    role: string;
} {
    return {
        workerId: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.workerId)),
        name: value.name,
        role: value.role
    };
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    germination: null;
} | {
    sowing: null;
} | {
    flowering: null;
} | {
    completed: null;
} | {
    harvesting: null;
} | {
    vegetative: null;
}): CropStage {
    return "germination" in value ? CropStage.germination : "sowing" in value ? CropStage.sowing : "flowering" in value ? CropStage.flowering : "completed" in value ? CropStage.completed : "harvesting" in value ? CropStage.harvesting : "vegetative" in value ? CropStage.vegetative : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    equipment: null;
} | {
    labour: null;
} | {
    transport: null;
} | {
    seeds: null;
} | {
    irrigation: null;
}): ExpenseCategory {
    return "other" in value ? ExpenseCategory.other : "equipment" in value ? ExpenseCategory.equipment : "labour" in value ? ExpenseCategory.labour : "transport" in value ? ExpenseCategory.transport : "seeds" in value ? ExpenseCategory.seeds : "irrigation" in value ? ExpenseCategory.irrigation : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    idle: null;
} | {
    planted: null;
} | {
    harvesting: null;
}): FieldStatus {
    return "idle" in value ? FieldStatus.idle : "planted" in value ? FieldStatus.planted : "harvesting" in value ? FieldStatus.harvesting : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    clay: null;
} | {
    silt: null;
} | {
    sandy: null;
} | {
    loamy: null;
}): SoilType {
    return "clay" in value ? SoilType.clay : "silt" in value ? SoilType.silt : "sandy" in value ? SoilType.sandy : "loamy" in value ? SoilType.loamy : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    equipment: null;
} | {
    seeds: null;
} | {
    fertilizer: null;
} | {
    pesticide: null;
}): ItemCategory {
    return "other" in value ? ItemCategory.other : "equipment" in value ? ItemCategory.equipment : "seeds" in value ? ItemCategory.seeds : "fertilizer" in value ? ItemCategory.fertilizer : "pesticide" in value ? ItemCategory.pesticide : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): TaskStatus {
    return "pending" in value ? TaskStatus.pending : "completed" in value ? TaskStatus.completed : "inProgress" in value ? TaskStatus.inProgress : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): TaskPriority {
    return "low" in value ? TaskPriority.low : "high" in value ? TaskPriority.high : "medium" in value ? TaskPriority.medium : value;
}
function from_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    harvesting: null;
} | {
    plowing: null;
} | {
    spraying: null;
} | {
    irrigation: null;
} | {
    general: null;
}): WorkerSkill {
    return "harvesting" in value ? WorkerSkill.harvesting : "plowing" in value ? WorkerSkill.plowing : "spraying" in value ? WorkerSkill.spraying : "irrigation" in value ? WorkerSkill.irrigation : "general" in value ? WorkerSkill.general : value;
}
function from_candid_variant_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CropRecord>): Array<CropRecord> {
    return value.map((x)=>from_candid_CropRecord_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Expense>): Array<Expense> {
    return value.map((x)=>from_candid_Expense_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FarmerProfile>): Array<FarmerProfile> {
    return value.map((x)=>from_candid_FarmerProfile_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Field>): Array<Field> {
    return value.map((x)=>from_candid_Field_n40(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InventoryItem>): Array<InventoryItem> {
    return value.map((x)=>from_candid_InventoryItem_n47(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n52(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkerProfile>): Array<WorkerProfile> {
    return value.map((x)=>from_candid_WorkerProfile_n59(_uploadFile, _downloadFile, x));
}
function to_candid_ExpenseCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenseCategory): _ExpenseCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Expense_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Expense): _Expense {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_FarmerProfile_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FarmerProfile): _FarmerProfile {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_InventoryItem_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InventoryItem): _InventoryItem {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_ItemCategory_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemCategory): _ItemCategory {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_SoilType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SoilType): _SoilType {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_TaskPriority_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskPriority): _TaskPriority {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_TaskStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): _TaskStatus {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_Task_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Task): _Task {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n70(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_WorkerProfile_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkerProfile): _WorkerProfile {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_WorkerSkill_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkerSkill): _WorkerSkill {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contact?: string;
    dailyWage: number;
    name: string;
    joiningDate: Timestamp;
    skill: WorkerSkill;
}): {
    contact: [] | [string];
    dailyWage: number;
    name: string;
    joiningDate: _Timestamp;
    skill: _WorkerSkill;
} {
    return {
        contact: value.contact ? candid_some(value.contact) : candid_none(),
        dailyWage: value.dailyWage,
        name: value.name,
        joiningDate: value.joiningDate,
        skill: to_candid_WorkerSkill_n11(_uploadFile, _downloadFile, value.skill)
    };
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contact?: string;
    name: string;
    village?: string;
    landAreaAcres: number;
    registrationDate: Timestamp;
}): {
    contact: [] | [string];
    name: string;
    village: [] | [string];
    landAreaAcres: number;
    registrationDate: _Timestamp;
} {
    return {
        contact: value.contact ? candid_some(value.contact) : candid_none(),
        name: value.name,
        village: value.village ? candid_some(value.village) : candid_none(),
        landAreaAcres: value.landAreaAcres,
        registrationDate: value.registrationDate
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    date: Timestamp;
    notes?: string;
    category: ExpenseCategory;
    amount: number;
}): {
    title: string;
    date: _Timestamp;
    notes: [] | [string];
    category: _ExpenseCategory;
    amount: number;
} {
    return {
        title: value.title,
        date: value.date,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        category: to_candid_ExpenseCategory_n3(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: TaskStatus;
    title: string;
    assignedWorker: WorkerId;
    dueDate: Timestamp;
    description?: string;
    priority: TaskPriority;
    fieldId: FieldId;
}): {
    status: _TaskStatus;
    title: string;
    assignedWorker: _WorkerId;
    dueDate: _Timestamp;
    description: [] | [string];
    priority: _TaskPriority;
    fieldId: _FieldId;
} {
    return {
        status: to_candid_TaskStatus_n21(_uploadFile, _downloadFile, value.status),
        title: value.title,
        assignedWorker: value.assignedWorker,
        dueDate: value.dueDate,
        description: value.description ? candid_some(value.description) : candid_none(),
        priority: to_candid_TaskPriority_n23(_uploadFile, _downloadFile, value.priority),
        fieldId: value.fieldId
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lowStockThreshold: number;
    name: string;
    unit: string;
    lastUpdated: Timestamp;
    quantity: number;
    category: ItemCategory;
}): {
    lowStockThreshold: number;
    name: string;
    unit: string;
    lastUpdated: _Timestamp;
    quantity: number;
    category: _ItemCategory;
} {
    return {
        lowStockThreshold: value.lowStockThreshold,
        name: value.name,
        unit: value.unit,
        lastUpdated: value.lastUpdated,
        quantity: value.quantity,
        category: to_candid_ItemCategory_n7(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    workerId?: string;
    name: string;
    role: string;
}): {
    workerId: [] | [string];
    name: string;
    role: string;
} {
    return {
        workerId: value.workerId ? candid_some(value.workerId) : candid_none(),
        name: value.name,
        role: value.role
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkerSkill): {
    harvesting: null;
} | {
    plowing: null;
} | {
    spraying: null;
} | {
    irrigation: null;
} | {
    general: null;
} {
    return value == WorkerSkill.harvesting ? {
        harvesting: null
    } : value == WorkerSkill.plowing ? {
        plowing: null
    } : value == WorkerSkill.spraying ? {
        spraying: null
    } : value == WorkerSkill.irrigation ? {
        irrigation: null
    } : value == WorkerSkill.general ? {
        general: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SoilType): {
    clay: null;
} | {
    silt: null;
} | {
    sandy: null;
} | {
    loamy: null;
} {
    return value == SoilType.clay ? {
        clay: null
    } : value == SoilType.silt ? {
        silt: null
    } : value == SoilType.sandy ? {
        sandy: null
    } : value == SoilType.loamy ? {
        loamy: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): {
    pending: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == TaskStatus.pending ? {
        pending: null
    } : value == TaskStatus.completed ? {
        completed: null
    } : value == TaskStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskPriority): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == TaskPriority.low ? {
        low: null
    } : value == TaskPriority.high ? {
        high: null
    } : value == TaskPriority.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpenseCategory): {
    other: null;
} | {
    equipment: null;
} | {
    labour: null;
} | {
    transport: null;
} | {
    seeds: null;
} | {
    irrigation: null;
} {
    return value == ExpenseCategory.other ? {
        other: null
    } : value == ExpenseCategory.equipment ? {
        equipment: null
    } : value == ExpenseCategory.labour ? {
        labour: null
    } : value == ExpenseCategory.transport ? {
        transport: null
    } : value == ExpenseCategory.seeds ? {
        seeds: null
    } : value == ExpenseCategory.irrigation ? {
        irrigation: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemCategory): {
    other: null;
} | {
    equipment: null;
} | {
    seeds: null;
} | {
    fertilizer: null;
} | {
    pesticide: null;
} {
    return value == ItemCategory.other ? {
        other: null
    } : value == ItemCategory.equipment ? {
        equipment: null
    } : value == ItemCategory.seeds ? {
        seeds: null
    } : value == ItemCategory.fertilizer ? {
        fertilizer: null
    } : value == ItemCategory.pesticide ? {
        pesticide: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
